# Generated by Django 4.0.4 on 2022-06-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0011_alter_issue_assignee_alter_issue_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="comment_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
